// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efvwcuonxakkjeufvbih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdndjdW9ueGFra2pldWZ2YmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTU4MjMsImV4cCI6MjA2MzQ5MTgyM30.c63pdtu1skQB5_XKz1Pz_7MLufaQl03_AA1beNM3Two";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);